[workspace]
resolver = "2"
members = ["lib"]

[dependencies]
hot-lib-reloader = { version = "0.7.0", optional = true } 
lib = { path = "lib" }


[package]
name = "bin"
version = "0.1.0"
edition = "2021"

[features]
default = []
reload = ["dep:hot-lib-reloader"]
